version: '3'
services:
  debian:
    build:
      context: .
      dockerfile: debian.Dockerfile
    image: clang-expand:debian
    command: ./build.sh
    volumes:
     - build:/home/build
     - llvm-build:/llvm/build
     - $PWD/../:/home/project
     - $PWD/bin:/home/build/bin

volumes:
  llvm-build:
  build:
